name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.3.1
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/KhatibFX/flutter_cache_manager.git
      ref: feature/wakecap_cache_manager_persistent
      path: ./flutter_cache_manager
  cached_network_image_platform_interface:
    git:
      url: https://github.com/KhatibFX/flutter_cached_network_image.git
      ref: feature/wakecap_cached_network_image_persistent
      path: ./cached_network_image_platform_interface
  web: ^1.0.0

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
