name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
version: 3.4.1

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/KhatibFX/flutter_cache_manager.git
      ref: feature/wakecap_cache_manager_persistent
      path: ./flutter_cache_manager
  octo_image: ^2.1.0
  cached_network_image_platform_interface:
    git:
      url: https://github.com/KhatibFX/flutter_cached_network_image.git
      ref: feature/wakecap_cached_network_image_persistent
      path: ./cached_network_image_platform_interface
  cached_network_image_web:
    git:
      url: https://github.com/KhatibFX/flutter_cached_network_image.git
      ref: feature/wakecap_cached_network_image_persistent
      path: ./cached_network_image_web


dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
